frontend/modules/profile/controllers/CategoryController.php
<?php

namespace frontend\modules\profile\controllers;
use common\models\BrandModels;

/**
 * ProductController implements the CRUD actions for Product model.
 */
class CategoryController extends BaseController
{
    public function actionAdd()
    {
        return $this->render('add');
    }

}

frontend/modules/profile/controllers/ProductController.php
<?php

namespace frontend\modules\profile\controllers;

use common\models\Albom;
use common\models\Category;
use common\models\CategoryField;
use common\models\Config;
use common\models\ProductField;
use frontend\models\ProductAddress;
use frontend\widgets\CategoryProfileFields;
use Yii;
use common\models\Product;
use common\models\search\ProductSearch;
use yii\data\ActiveDataProvider;
use yii\helpers\ArrayHelper;
use yii\web\NotFoundHttpException;
use frontend\widgets\CategoryFields;


/**
 * ProductController implements the CRUD actions for Product model.
 */
class ProductController extends BaseController
{

    /**
     * Displays a single Product model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $dataProvider = new ActiveDataProvider([
            'query' => ProductField::find()->where(['product_id' => $id])
        ]);
        return $this->render('view', [
            'model' => $this->findModel($id),
            'dataProvider' => $dataProvider
        ]);
    }

    /**
     * Lists all Product models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProductSearch();
        $searchModel->user_id = Yii::$app->user->identity->id;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);


        $searchModelActive= new ProductSearch();
        $searchModelActive->user_id = Yii::$app->user->identity->id;
        $searchModelActive->status = 1;
        $dataProviderActive = $searchModelActive->search(Yii::$app->request->queryParams);

        $searchModelPassive= new ProductSearch();
        $searchModelPassive->user_id = Yii::$app->user->identity->id;
        $searchModelPassive->status = 0;
        $dataProviderPassive = $searchModelPassive->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'dataProviderActive' => $dataProviderActive,
            'dataProviderPassive' => $dataProviderPassive,
        ]);
    }

    /**
     * Lists all Product models.
     * @return mixed
     */
    public function actionPreferred()
    {
        $cookiesFavourite = Config::getUserFavorites();

        $searchModel = new ProductSearch();
        $queryParams = array_merge(['cookiesFavourite' => $cookiesFavourite], Yii::$app->request->queryParams);
        $dataProvider = $searchModel->search($queryParams);

        return $this->render('preferred', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actions()
    {
        $actions = parent::actions();

        return $actions;
    }

    /**
     * Creates a new Product model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id)
    {
        if ($category = Category::findOne($id)) {
            if ($category->childs) {
                return $this->goHome();
            }
        }

        $fieldModel = new ProductField();
        $imageAlbom = new Albom();
        $productAddress = new ProductAddress();
        $model = new Product();
        $allErrors = [];

        $model->category_id = $id;

        if ($model->load(Yii::$app->request->post())) {


            if ($fieldModel->load(Yii::$app->request->post())) {

                /*validation category fields*/
                $validate = CategoryField::find()->where(['category_fields_wish_id' => $model->category_fields_wish_id])->all();

                $allErrors = $this->formValidate($validate, $fieldModel);
                $fieldModel->validate();

                if ($fieldModel->hasErrors() || $allErrors) {
                    return $this->render('create', [
                        'allErrors' => $allErrors,
                        'fieldModel' => $fieldModel,
                        'imageAlbom' => $imageAlbom,
                        'model' => $model,
                        'productAddress' => $productAddress,
                    ]);
                }
                /*end validation*/
                $model->user_id = Yii::$app->user->identity->id;
                $model->save();

                foreach ($fieldModel->allCategoryFields as $key => $value) {
                    $categoryField = CategoryField::findOne(['id' => $key]);
                    if ($categoryField && $value) {
                        $fieldModel->deleteAll(['category_field_id' => $categoryField->id, 'product_id' => $model->id]);
                        if ($categoryField->type == CategoryField::typeSelect ||
                            $categoryField->type == CategoryField::typeCheckbox ||
                            $categoryField->type == CategoryField::typeRadio ||
                            ($categoryField->type == CategoryField::typeInput && $categoryField->allow_multiple == CategoryField::multipleYes)
                        ) {
                            $value = (array)$value;

                            if (!$categoryField->allow_multiple) {
                                $value = [$value[0]];
                            }


                            foreach ($value as $fieldValue) {
                                $newModel = new ProductField();
                                $newModel->product_id = $model->id;
                                $newModel->category_field_id = $categoryField->id;
                                if ($categoryField->allow_range) {
                                    $newModel->value = $fieldValue;
                                } else {
                                    $newModel->category_field_value_id = $fieldValue;
                                }
                                $newModel->save();
                            }

                        } elseif (
                            ($categoryField->type == CategoryField::typeInput && $categoryField->allow_multiple == CategoryField::multipleNo)
                            ||
                            $categoryField->type == CategoryField::typeTextArea
                        ) {
                            $newModel = new ProductField();
                            $newModel->product_id = $model->id;
                            $newModel->category_field_id = $key;
                            $newModel->value = $value;
                            if ($newModel->save()) {
                                if ($categoryField->name == 'Rate' || $categoryField->name == 'Price') {
                                    if ($categoryField->name == 'Rate') {
                                        $model->rate_id = $value;
                                    } elseif ($categoryField->name == 'Price') {
                                        $model->price = $value;
                                    }
                                    $model->save();
                                }
                            }
                        }
                    }
                }

                /* upload images */
                if ($imageAlbom->load(Yii::$app->request->post())) {
                    $model->uplodeImages($imageAlbom, $model);
                }

                /* product address */
                if ($productAddress->load(Yii::$app->request->post())) {
                    $productAddress->product_id = $model->id;
                    $productAddress->save();
                }
            }

            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'allErrors' => $allErrors,
                'fieldModel' => $fieldModel,
                'imageAlbom' => $imageAlbom,
                'model' => $model,
                'productAddress' => $productAddress,
            ]);
        }
    }


    public function formValidate($validate, $fieldModel)
    {
        if ($validate) {
            foreach ($validate as $validate) {
                if ($validate->required == CategoryField::requiredYes) {
                    if (isset($fieldModel->allCategoryFields[$validate->id]) &&
                        !$fieldModel->allCategoryFields[$validate->id]
                    ) {
                        $fieldModel->addError($validate->name, "$validate->name Can not be blank");
                    } elseif (!isset($fieldModel->allCategoryFields[$validate->id])) {
                        $fieldModel->addError($validate->name, "$validate->name Can not be blank");
                    }
                }

                $s= [];
                foreach ($fieldModel->attributes() as $key => $value){
                    $name = str_replace(' ','_', strtolower($validate->name));
                    $s[] = $value;

                    if($value == $name && isset($fieldModel->allCategoryFields[$validate->id])){
                        $fieldModel->{$name} = $fieldModel->allCategoryFields[$validate->id];
                    }
                }

                foreach ($fieldModel->allCategoryFields as $key => $value) {
                    $categoryField = CategoryField::findOne(['id' => $key]);}


                if (isset($fieldModel->allCategoryFields[$validate->id]) && $fieldModel->allCategoryFields[$validate->id]) {
                    $valCheck = $fieldModel->allCategoryFields[$validate->id];
                    if ($validate->type == CategoryField::typeSelect ||
                        $validate->type == CategoryField::typeCheckbox ||
                        $validate->type == CategoryField::typeRadio ||
                        ($validate->type == CategoryField::typeInput && $validate->allow_multiple == CategoryField::multipleYes)
                    ) {

                        //validate when use db and multiple value
                        if($validate->type == CategoryField::typeInput){
                            if (is_array($valCheck)) {

frontend/modules/profile/controllers/UserController.php
<?php

namespace frontend\modules\profile\controllers;

use common\models\User;
use common\models\UserFollow;
use frontend\modules\profile\models\PasswordForm;
use Yii;
use yii\data\ActiveDataProvider;
use yii\data\Pagination;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;
use Exception;

/**
 * UserController implements the CRUD actions for User model.
 */

class UserController  extends BaseController
{
    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate()
    {
        $id = \Yii::$app->user->identity->id;
        $model = $this->findModel($id);

        $oldPassword = $model->password_hash;
        $oldImage = $model->image;
        $model->password_hash = null;

        if ($model->load(Yii::$app->request->post())) {

            $model->birth_day = date('Y-m-d',strtotime($model->birth_day));

            if(!$model->password_hash){
                $model->password_hash = $oldPassword;
            }else{
                $model->setPassword($model->password_hash);
            }

            if(!$model->image){
                $model->image = $oldImage;
            }

            unset($model->social_users_favourite);

            if($model->validate()  && $model->save()){
                $model->image = UploadedFile::getInstance($model, 'image');
                if($model->image) {
                    $model->image = Yii::$app->uploadAvatar->uploadImageAvatar($model->image);
                    $model->save(false);
                }

                Yii::$app->session->setFlash('success',Yii::t('app', 'My user information updated successfully'));

                return $this->redirect(['update']);
            }

            return $this->redirect(['update']);
        }

        return $this->render('_form',[
            'model' => $model
        ]);
    }


    public function actionChangePassword()
    {

        $model = new PasswordForm;

        $modeluser = \Yii::$app->user->identity;

        if ($model->load(Yii::$app->request->post())) {
            if ($model->validate()) {
                try {
                    $modeluser->password_hash = Yii::$app->security->generatePasswordHash($_POST['PasswordForm']['newpass']);
                    unset($modeluser->social_users_favourite);
                    if ($modeluser->save()) {
                        Yii::$app->session->setFlash('success',Yii::t('app', 'Password changed successfully'));
                        return $this->redirect(['change-password']);
                    } else {
                        Yii::$app->getSession()->setFlash(
                            'error', 'Password not changed'
                        );
                        return $this->redirect(['change-password']);
                    }
                } catch (Exception $e) {
                    Yii::$app->getSession()->setFlash(
                        'error', "{$e->getMessage()}"
                    );
                    return $this->render('change-password', [
                        'model' => $model
                    ]);
                }
            } else {
                return $this->render('change-password', [
                    'model' => $model
                ]);
            }
        } else {
            return $this->render('change-password', [
                'model' => $model
            ]);
        }
    }

    public function actionFollow()
    {
        $query = UserFollow::find()->where(['sender_id'=> Yii::$app->user->identity->id,'follow' => UserFollow::followYes ]);

        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count(), 'pageSize'=>10]);
        $models = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();

        return $this->render('follow', [
            'models' => $models,
            'pages' => $pages,
        ]);
    }

    public function actionFollowDelete()
    {
        $receiver_id = Yii::$app->request->post('id');
        if(!$receiver_id) return false;

        $query = UserFollow::find()->where(['sender_id'=> Yii::$app->user->identity->id,'receiver_id' => $receiver_id])->one();
        if($query && $query->delete()){
            return json_encode(['success' => 'deleted']);
        }
        return false;
    }


    /**
     * Finds the Product model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Product the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/modules/profile/views/product/_form.php
<?php

use borales\extensions\phoneInput\PhoneInput;
use common\models\Config;
use common\models\Geo;
use kartik\file\FileInput;
use kartik\select2\Select2;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Product */
/* @var $form yii\widgets\ActiveForm */
/* @var $shops array */
/* @var $categories array */
/* @var $brands array */


//print_r($fieldModel->getErrors());
?>

<div class="product-form">
    <?php if ($fieldModel->hasErrors()): ?>
        <?php if ($fieldModel->getErrors()): ?>
            <div class="alert alert-danger">
            <?php foreach ($fieldModel->getErrors() as $errors): ?>
                    <?php foreach ($errors as $error): ?>
                        <?= $error ?><br>
                    <?php endforeach; ?>
            <?php endforeach; ?>
            </div>
        <?php endif; ?>
    <?php endif; ?>

    <?php if ($allErrors): ?>
        <?php if ($allErrors): ?>
            <div class="alert alert-danger">
            <?php foreach ($allErrors as $errors): ?>
                    <?php foreach ($errors as $error): ?>
                        <?= $error ?><br>
                    <?php endforeach; ?>
            <?php endforeach; ?>
            </div>
        <?php endif; ?>
    <?php endif; ?>

    <?php if ($categoryWish = $model->category->categoryFieldsWish): ?>
        <?php
        $form = ActiveForm::begin([
            'enableClientValidation' => true,
            'enableClientValidation' => true,
            'options' => [
                'enctype' => 'multipart/form-data',
                'data-toggle' => 'validator',
                'role' => 'form',
            ]]);
        ?>

        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5><?= Html::encode($this->title) ?></h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>

                </div>
            </div>
            <div class="ibox-content">
                <?php // $form->field($model, 'imageFile')->fileInput(); ?>

                <div class="form-radio form-group ">
                    <?php
                    foreach ($categoryWish as $key => $value): ?>
                        <?php
                        $checked = null;

                        if ((!$model->category_fields_wish_id && $key == 0) || ($value['id'] == $model->category_fields_wish_id)) {
                            $checked = true;
                        }

                        echo Html::radio('Product[category_fields_wish_id]', $checked, ['value' => $value['id'], 'label' => $value['value_' . Yii::$app->language], 'class' => 'form-radio-checkbox1']);
                        ?>
                    <?php endforeach; ?>
                </div>
                <?= $form->field($model, 'title')->textInput() ?>

                <div class="form-category-filed">
                    <?= frontend\widgets\CategoryFields::widget(['model' => $model, 'fieldModel' => $fieldModel, 'id' => $model->category_fields_wish_id,'profile' => true]); ?>
                </div>

                <?= $form->field($model, 'description')->textarea(); ?>

                <?php if ($model->isNewRecord) {
                    echo FileInput::widget([
                        //'name' => 'attachment',
                        'options' => [
                            'multiple' => true,
                            'accept' => 'image/*',
                            'paramName' => 'image',
                        ],
                        'model' => $imageAlbom,
                        'attribute' => 'image[]',
                        'pluginOptions' => [
                            'allowedFileExtensions' => ["jpg", "png", "gif", "jpeg"],
                            'showPreview' => true,
                            'showCaption' => true,
                            'showRemove' => true,
                            'message' => "hello",
                            'showUpload' => false,
                            'removeLabel' => Yii::t('app', 'Remove'),
                            'browseLabel' => Yii::t('app', 'Add'),
                            'maxFileCount' => 7,
                            'initialCaption' => Yii::t('app', 'Add Photos'),
                        ]
                    ]);
                } else {
                    echo FileInput::widget([
                        //'name' => 'attachment',
                        'options' => [
                            'multiple' => true,
                            'accept' => 'image/*'
                        ],
                        'model' => $imageAlbom,
                        'attribute' => 'image[]',
                        'pluginOptions' => [
                            'showPreview' => true,
                            'showCaption' => true,
                            'showRemove' => true,
                            'showUpload' => false,
                            'removeLabel' => Yii::t('app', 'Remove'),
                            'browseLabel' => Yii::t('app', 'Add'),
                            'allowedFileExtensions' => ["jpg", "png", "gif", "jpeg"],
                            'maxFileCount' => 7 - $imageCount,
                            'initialPreview' => $allImage,
                            'overwriteInitial' => false,
                            'initialPreviewAsData' => true,
                            'initialCaption' => Yii::t('app', 'Add Photos'),
                            'initialPreviewConfig' => $allImageId,
                            'maxFileSize' => 2800,
                            'uploadUrl' => Url::to(['#']),
                            'uploadAsync' => true,
                        ],
                        'pluginEvents' => [
                            'filesorted' => 'function(event, params) { $.ajax({
                                     url: "' . Url::to(['/profile/product/sort-image']) . '",
                                     type: "post",
                                     data: { previewId:params.stack[params.newIndex].key, oldIndex:params.oldIndex, newIndex:params.newIndex, stack:params.stack},
                                    }).done(function( msg ) { 
                                                      });
                                                                        ;

                                    }',
                        ],

                    ]);
                }
                ?>

            </div>
        </div>

        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>
                    <?= Yii::t('app', 'Contact Information How would you like to be contacted?') ?>
                </h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>

                </div>
            </div>
            <div class="ibox-content">
                <?= $form->field($productAddress, 'address')->textInput() ?>

                <?= $form->field($productAddress, 'city_id')->widget(Select2::classname(), [
                    'data' => Config::getRegionList(),
                    'options' => ['placeholder' => 'Select a state ...'],
                    'pluginOptions' => [
                        'allowClear' => true
                    ],
                ]); ?>

                <?= $form->field($productAddress, 'number_one')
                    ->widget(PhoneInput::className(), [
                        'options' => ['class' => 'form-control'],
                        'jsOptions' => [
                            'preferredCountries' => ['LT'],
                            'nationalMode' => false
                        ]
                    ]);
                ?>

                <?= $form->field($productAddress, 'number_two')
                    ->widget(PhoneInput::className(), [
                        'options' => ['class' => 'form-control'],
                        'jsOptions' => [
                            'preferredCountries' => ['LT'],
                            'nationalMode' => false
                        ]
                    ]);
                ?>
            </div>
        </div>

        <div class="form-group">
            <?= Html::submitButton($model->isNewRecord ? Yii::t('app','Create') : Yii::t('app','Update'), ['class' => $model->isNewRecord ? 'btn  btn-primary' : 'btn btn-primary']) ?>
        </div>


        <?php ActiveForm::end(); ?>
    <?php endif; ?>
</div>


<?php
$urlField = Url::toRoute(['/profile/product/category-update-field/']);
$modelGet = Url::toRoute(['/profile/category/get-model-list/']);
$script = <<< JS
 $(document).ready(function(){ 
   
     
    $('.form-radio-checkbox1').click(function(){
        var id = $(this).val();
        var catId = {$model->category_id};
       var csrfToken = $('meta[name="_csrf"]').attr("content");

        $.ajax({
              url: "$urlField",
              type: 'POST',
              data: {
                  'id' : id,
                  'catId' : catId,
                  _csrf : csrfToken
              },
              success: function(data) { 
                      $('.form-category-filed').html(data);
                      $('#w0').validator('destroy');
                      $('#w0').validator();
              },
              error: function(e) { 
              }
         }); 
          $('#w0').validator('destroy');
          $('#w0').validator();
       
    });
    
    if($('.form-radio-checkbox1').length){
          //  $('.form-radio-checkbox1').first().trigger('click');
    }

    
     $(document).on('change',"#form-Brand",function(){
        var id = $(this).val();
        $.ajax({
             type: "post",
             url:  "$modelGet",
             data: {
                id: id
             },
             dataType: "html",
             success: function(data) {
                $("#form-Model").html(data);
             },
         });
    })
        
}); 
JS;
$this->registerJs($script);
?>

frontend/modules/profile/views/product/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\ProductSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="product-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'category_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/modules/profile/views/product/product_grid.php
<?php

use kartik\field\FieldRange;
use kartik\file\FileInput;
use kartik\growl\Growl;
use kartik\select2\Select2;
use kartik\switchinput\SwitchInput;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\jui\DatePicker;

/* @var $this yii\web\View */
/* @var $model common\models\Product */
/* @var $form yii\widgets\ActiveForm */

$cookiesFavourite = Yii::$app->request->cookies->getValue('favourite', []);
$favorite = intval(in_array($model->id, $cookiesFavourite));
$currency = Yii::$app->session->get('currency');

if(!Yii::$app->user->isGuest) {
    $user = yii::$app->user->identity;
    if ($user->social_users_favourite) {
        $favorite = intval(in_array($model->id, unserialize($user->social_users_favourite)));
    }
}

?>

<div class="product-content">
    <div class="col-md-4 col-sm-4 col-xs-6 product-child">
        <div class="product">
            <div class="">
                <a href="<?= Url::to(["category/view",'id' => $model->id ])?>">
                    <img src="<?= $model->productFirstImage ? $model->productFirstImage : '/images/nopicture.png';  ?>">
                </a>
                <?php  if ($model->rate_id && $model->price): ?>
                    <div class="item-price">
                    <span data-bind="text: Price">
                        <?= \common\models\Currency::showCurrency(ArrayHelper::getValue($model,'price'), ArrayHelper::getValue($model,'rate.name_'.Yii::$app->language)) ?>
                    </span>
                    </div>
                <?php endif; ?>
            </div>
            <a href="<?= Url::to(["category/view", 'id' => $model->id ])?>">
                <span class="slide-title"><?= $model->title ?></span>
            </a>
            <div class="favourite"  data-id="<?= $model->id; ?>" data-favourite="<?= $favorite ?>"><i title="<?= yii::t('app','Saved Ads')?>" class="fa fa-star<?= $favorite? '' : '-o'?>"></i></div>
        </div>
    </div>
</div>

frontend/modules/profile/views/product/product_list.php
<?php

use common\models\Config;
use kartik\field\FieldRange;
use kartik\file\FileInput;
use kartik\growl\Growl;
use kartik\select2\Select2;
use kartik\switchinput\SwitchInput;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\jui\DatePicker;

/* @var $this yii\web\View */
/* @var $model common\models\Product */
/* @var $form yii\widgets\ActiveForm */

?>


<dl>
    <dt>
        <img src="<?= $model->productFirstImage ? $model->productFirstImage : '/images/nopicture.png'; ?>">
        <strong>
            <?= ArrayHelper::getValue($model, 'price') . ' ' . ArrayHelper::getValue($model, 'rate.name_'.Yii::$app->language) ?>
        </strong>
        <span class="title"> <a target="_blank" href="<?= Url::to(['/category/view','id' =>$model->id ]) ?>"> <?= Config::replaceTitle($model->title, '70') ?></a></span>
    </dt>
    <dd>
        <p class="profile-description">
            <?= Config::replaceTitle($model->description, '200') ?>
        </p>
    </dd>

    <?php if (Yii::$app->controller->action->id !== "preferred"): ?>
        <dd class="action">

            <a href="<?= Url::to(['product/view', 'id' => $model->id]) ?> " class="btn btn-info" title="View"
               aria-label="View">
                <?= Yii::t('app','View') ?>
            </a>
            <a href="<?= Url::to(['product/update', 'id' => $model->id]) ?>" class="btn btn-primary" title="Update"
               aria-label="Update">
                <?= Yii::t('app', 'Update') ?>
            </a>
            <a href="<?= Url::to(['product/delete', 'id' => $model->id]) ?>" class="btn btn-danger" title="Delete"
               aria-label="Delete" data-confirm=" <?= Yii::t('app', 'Are you sure you want to delete this item?') ?>"
               data-method="post">
                <?= Yii::t('app','Delete') ?>
            </a>
        </dd>
    <?php endif; ?>


    <?php if (Yii::$app->controller->action->id == "preferred"):
        $cookiesFavourite = Yii::$app->request->cookies->getValue('favourite', []);
        $favorite = intval(in_array($model->id, $cookiesFavourite));
        $currency = Yii::$app->session->get('currency');

        if(!Yii::$app->user->isGuest) {
            $user = yii::$app->user->identity;
            if ($user->social_users_favourite) {
                $favorite = intval(in_array($model->id, unserialize($user->social_users_favourite)));
            }
        }

        ?>
        <dd class="action">
            <a href="#" class="btn btn-danger favourite favourite-profile" title="Delete"  data-id="<?= $model->id; ?>" data-favourite="<?= $favorite ?>">
                <?= Yii::t('app', 'Delete') ?>
            </a>
        </dd>

        <?php
        if(yii::$app->controller->action->id == 'preferred'){
            $this->registerJs('
                $(".favourite-profile").each(function(){
                    $(this).click(function(){
                            $(this).closest("div").remove(); 
                    });
  
                })
            ');
        }
        ?>

    <?php endif; ?>
</dl>