common/models/Banner.php
<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\helpers\ArrayHelper;
use common\models\BannerPages;
use common\models\GeoCountry;

/**
 * This is the model class for table "banner".
 *
 * @property integer $id
 * @property string $name
 * @property string $title
 * @property string $type
 * @property string $content
 * @property string $destination_url
 * @property integer $width
 * @property integer $height
 * @property string $is_active
 * @property string $is_limit_ended
 * @property integer $banner_placement_id
 * @property integer $banner_page_id
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property BannerAge $bannerAge
 * @property BannerPages $bannerPage
 * @property BannerPlacement $bannerPlacement
 * @property BannerRules[] $bannerRules
 * @property BannerStat[] $bannerStats
 */
class Banner extends \yii\db\ActiveRecord
{
    public $file;
    public $code;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%banner}}';
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'title', 'type', 'banner_placement_id', 'banner_page_id','is_active'], 'required'],
            [['content', 'is_active', 'is_limit_ended','file_extension_type'], 'string'],
            [['file'], 'file'],
            [['code'],'string'],
            [['type','is_active','is_limit_ended'], 'in', 'range' => [0, 1]],

            [['file'], 'required', 'on' =>'create','when' => function ($model) {
                if ($model->type == '0' ) {
                    return true;
                } elseif ($model->type == '1') {
                    return false;
                }
            }, 'whenClient' => "function (attribute, value) {
                   var name = $('#banner-type').val();
                   if(name=='0'){return name;} 
              }"
            ],

            [['code'], 'required', 'when' => function ($model) {
                if ($model->type == '1' ) {
                    return true;
                } elseif ($model->type == '0') {
                    return false;
                }
            }, 'whenClient' => "function (attribute, value) {
                   var name = $('#banner-type').val();
                   if(name=='1'){return name;} 
                }"
            ],


            [['width', 'height', 'banner_placement_id', 'banner_page_id', 'created_at', 'updated_at',], 'integer'],
            [['name', 'title', 'destination_url'], 'string', 'max' => 255],
            [['banner_page_id'], 'exist', 'skipOnError' => true, 'targetClass' => BannerPages::className(), 'targetAttribute' => ['banner_page_id' => 'id']],
            [['banner_placement_id'], 'exist', 'skipOnError' => true, 'targetClass' => BannerPlacement::className(), 'targetAttribute' => ['banner_placement_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Banner Name'),
            'title' => Yii::t('app', 'Title'),
            'type' => Yii::t('app', 'Type'),
            'content' => Yii::t('app', 'Content'),
            'destination_url' => Yii::t('app', 'Destination Url'),
            'width' => Yii::t('app', 'Width'),
            'height' => Yii::t('app', 'Height'),
            'is_active' => Yii::t('app', 'Status'),
            'is_limit_ended' => Yii::t('app', 'Limit Ended'),
            'banner_placement_id' => Yii::t('app', 'Placement Name'),
            'banner_page_id' => Yii::t('app', 'Banner Page'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }
    

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBannerPage()
    {
        return $this->hasOne(BannerPages::className(), ['id' => 'banner_page_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBannerPlacement()
    {
        return $this->hasOne(BannerPlacement::className(), ['id' => 'banner_placement_id']);
    }

   /* public function getBannerPlacementChecked()
    {
        $pageId = $this->banner_page_id;
        $BannerPlacements = BannerPlacement::find()->where(['banner_pages_id' => $this->banner_page_id])->all();
        if(!$BannerPlacements) return false;
        $getData = [];
        foreach ($BannerPlacements as $BannerPlacement){
            $getData[$BannerPlacement->id] = $BannerPlacement->width . '-' . $BannerPlacement->height;
        };
        return $getData;
    }*/


    public  function getBannerPlacementChecked() {
        $options = [];

        $pageId = $this->banner_page_id;
        $BannerPlacements = BannerPlacement::find()->where(['banner_pages_id' => $this->banner_page_id])->all();
        if(!$BannerPlacements) return false;


        foreach($BannerPlacements as   $p) {
            $modelPlacementsGroup = BannerPlacement::find()->where(['banner_pages_id' => $p->banner_pages_id,'is_mobile' => $p->is_mobile])->all();
            //$placemennt[] = "<optgroup  label='".$modell->bannerMobile[$modell->is_mobile]."'>";

            $child_options = [];
            foreach($modelPlacementsGroup as $child) {
                $child_options[$child->id] = $child->width . '-' . $child->height;
            }
            $options[$this->bannerMobile[$p->is_mobile] ] = $child_options;
        }
        return $options;
    }



    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBannerRules()
    {
        return $this->hasMany(BannerRules::className(), ['banner_id' => 'id']);
    }

    public function getBannerCountryBanner()
    {
        return $this->hasMany(BannerCountry::className(), ['banner_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */

    public function getBannerStats()
    {
        return $this->hasMany(BannerStat::className(), ['banner_id' => 'id']);
    }



    public function getBannerCountryIndex($dataId){
        if(!$dataId) return false;
        $countryBnnerID = BannerCountry::find()->select('country_include_id')->where(['banner_id' => $dataId])->asArray()->all();
        if(!$countryBnnerID) return false;
        $countryId = [];
        foreach ($countryBnnerID as $country){
            $countryId[] = $country['country_include_id'];
        }
        $countrys = GeoCountry::find()->select('name')->where(['geonameId' => $countryId])->all();
        if(!$countrys) return false;
        $countrysString = '';
        foreach ($countrys as $key => $country){
            $countrysString.= $country->name.', ';
        }
        $countrysString = substr($countrysString,0,-2);
        return $countrysString;
    }

    public function getBannerPages()
    {
        return ArrayHelper::map(BannerPages::find()->asArray()->all(), 'id', 'name');
    }

    public function getBannerStatus(){
        return [
            0 => 'Off',
            1 => 'On',
        ];
    }

    public function getBannerType(){
        return [
            0 => 'Medium',
            1 => 'Cod',
        ];
    }

    public function getBannerMobile(){
        return [
            0 => 'Desktop',
            1 => 'Tablet',
            2 => 'Mobile',
        ];
    }

    public function getBannerSex(){
        return [
            2 => 'All',
            0 => 'Male',
            1 => 'Female',
        ];
    }



    public function getBannerCountry()
    {
        return ArrayHelper::map(GeoCountry::find()->asArray()->all(), 'geonameId', 'name');
    }

}

backend/controllers/BannerController.php
<?php

namespace backend\controllers;

use common\models\BannerPlacement;
use Yii;
use common\models\Banner;
use common\models\search\BannerSearch;
use common\models\BannerPages;
use common\models\BannerRules;
use common\models\BannerCountry;
use yii\helpers\Json;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;

/**
 * BannerController implements the CRUD actions for Banner model.
 */
class BannerController extends BaseController
{


    /**
     * Lists all Banner models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BannerSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        if (Yii::$app->request->post('hasEditable')) {
            $bookId = Yii::$app->request->post('editableKey');
            $model = Banner::findOne($bookId);

            $out = Json::encode(['output'=>'', 'message'=>'']);

            $posted = current($_POST['Banner']);
            $post = ['Banner' => $posted];

            // load model like any single model validation
            if ($model->load($post)) {
                // can save model or do something before saving model
                $model->save(false);
                $output = '';
                if (isset($posted['name'])) {
                    $output = $model->name;
                }

                $out = Json::encode(['output'=>$output, 'message'=>'']);
            }
            echo $out;
            return;
        }

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionMultipleDelete()
    {
        if(Yii::$app->request->isAjax == true) {
            $ids = Yii::$app->request->post('row_id');
            if(isset($ids) && $ids) {
                Banner::deleteAll(['id' => $ids]);
            }
        }
    }

    /**
     * Displays a single Banner model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Banner model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */

    public function actionCreate()
    {
        $model = new Banner();
        $bannerRules = new BannerRules();
        $bannerCountry = new BannerCountry();
        $model->scenario = "create";

        if ($model->load(Yii::$app->request->post())) {
            $fileType = '';
            $img = ["jpg", "png", "gif", "jpeg"];
            $video  = ["mp4","m4v", "mov", "flv", "f4v", "ogg", "ogv", "wmv", "vp6", "vp5", "mpg", "avi", "mpeg", "webm"];
            $flash  = ["swf"];
            if($model->type == 0 ) {
                $files = UploadedFile::getInstances($model, 'file');

                if ($files && is_array($files)) {
                    foreach ($files as $file) {
                        $imageRandName = rand(1, 9999999);
                        $file->saveAs(Yii::getAlias('@frontend/web') . '/banners' . '/' . md5($imageRandName) . '.' . $file->extension);
                        $fileName = md5($imageRandName) . '.' . $file->extension;

                        if(in_array($file->extension ,$img)) {
                            $fileType  = 'image';
                        }elseif(in_array($file->extension ,$video)){
                            $fileType  = 'video';
                        }elseif(in_array($file->extension ,$flash)){
                            $fileType  = 'flash';
                        }
                    }
                    $model->file_extension_type = $files[0]->type;
                    $model->content = $fileName;
                    $model->type = 0;
                }
            }elseif ($model->type == 1) {
                if ($model->code) {
                    $model->content = $model->code;
                    $model->type = 1;
                    $fileType  = 'code';
                    $model->file_extension_type = '';
                }
            }
            $model->save();
            if($bannerRules->load(Yii::$app->request->post())){
                 $bannerRules->file_type = $fileType;
                 $bannerRules->banner_id = $model->id;
                $bannerRules->save();
            }

            if($bannerCountry->load(Yii::$app->request->post())){
                if($bannerCountry->country_include_id) {
                    foreach ($bannerCountry->country_include_id as $key) {
                        $bannerCountry = new BannerCountry();
                        $bannerCountry->banner_id = $model->id;
                        $bannerCountry->country_include_id = $key;
                        $bannerCountry->save();
                    }
                }

            }


          //  return $this->redirect(['view', 'id' => $model->id]);
               return $this->redirect(['index']);
        } else {
            if(yii::$app->request->isAjax) {
                return $this->renderAjax('create', [
                    'model' => $model,
                    'bannerRules' => $bannerRules,
                    'bannerCountry' => $bannerCountry,
                ]);
            }else{
                return $this->render('create', [
                    'model' => $model,
                    'bannerRules' => $bannerRules,
                    'bannerCountry' => $bannerCountry,
                ]);
            }
        }
    }

    /**
     * Updates an existing Banner model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionImageDelete()
    {
        if (isset($_POST['key']) && $_POST['key']) {
            $key = intval(abs($_POST['key']));
            $banner = Banner::find()->where(['id' => $key])->one();
            if($banner !== null) {
                $banner->content = '';
                $banner->save();
            }
            echo 1;
        }
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $bannerRules = BannerRules::find()->where(['banner_id' => $id])->one();
        $bannerCountryData = BannerCountry::find()->select('country_include_id')->where(['banner_id' => $id])->asArray()->all();
        $country = [];
        foreach ($bannerCountryData as $key ){
            $country[] = $key['country_include_id'];
        }
        $bannerCountry = new BannerCountry();

        $allimageid = [];$allimage = [];

        $fileTypePreview = '';

        if($model->type == 0) {

            if($bannerRules->file_type == 'video'){
                $fileTypePreview = 'video';
            }elseif ($bannerRules->file_type == 'image'){
                $fileTypePreview = 'image';
            }elseif ($bannerRules->file_type == 'flash'){
                $fileTypePreview = 'flash';
            }

            if($model->content) {
                $allimageid[] = array('url' => \yii\helpers\Url::toRoute([\Yii::$app->request->baseUrl . '/admins/banner/image-delete']), 'key' => $model->id,'filetype'=> $model->file_extension_type);
                $allimage[] =  '/banners/' . $model->content;
            }
        }



        if($bannerRules->limit_end_date == '01-01-1970'){
            $bannerRules->limit_end_date = null;
        }

        $fileType=$bannerRules->file_type;
        if ($model->load(Yii::$app->request->post())) {
            $img = ["jpg", "png", "gif", "jpeg"];
            $video  = ["m4v", "mov", "flv", "f4v", "ogg", "ogv", "wmv", "vp6", "vp5", "mpg", "avi", "mpeg", "webm","mp4"];
            $flash  = ["swf"];

            if($model->type == 0 ) {
                $files = UploadedFile::getInstances($model, 'file');

                if ($files && is_array($files)) {
                    foreach ($files as $file) {

                        $imageRandName = rand(1, 9999999);
                        $file->saveAs(Yii::getAlias('@frontend/web') . '/banners' . '/' . md5($imageRandName) . '.' . $file->extension);
                        $fileName = md5($imageRandName) . '.' . $file->extension;
                        if(in_array($file->extension ,$img)) {
                            $fileType  = 'image';
                        }elseif(in_array($file->extension ,$video)){
                            $fileType  = 'video';
                        }elseif(in_array($file->extension ,$flash)){
                            $fileType  = 'flash';
                        }

                    }
                    $model->file_extension_type = $files[0]->type;
                    $model->content = $fileName;
                    $model->type = 0;
                }
            }elseif ($model->type == 1) {
                if ($model->code) {
                    $model->content = $model->code;
                    $model->type = 1;
                    $fileType  = 'code';
                    $model->file_extension_type = '';
                }
            }
            $model->save();

            if($bannerRules->load(Yii::$app->request->post())){
                $bannerRules->file_type = $fileType;
                $bannerRules->banner_id = $model->id;
                $bannerRules->save();
            }


            if($bannerCountry->load(Yii::$app->request->post())){
                BannerCountry::deleteAll('banner_id = :id', [':id'=>$id]);
                if($bannerCountry->country_include_id) {
                    foreach ($bannerCountry->country_include_id as $key) {
                        $bannerCountry = new BannerCountry();
                        $bannerCountry->banner_id = $model->id;
                        $bannerCountry->country_include_id = $key;
                        $bannerCountry->save();
                    }
                }

            }
            return $this->redirect(['index']);

backend/views/banner/_form.php
<?php

use kartik\field\FieldRange;
use kartik\file\FileInput;
use kartik\growl\Growl;
use kartik\select2\Select2;
use kartik\switchinput\SwitchInput;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\jui\DatePicker;

/* @var $this yii\web\View */
/* @var $model frontend\models\Banner */
/* @var $form yii\widgets\ActiveForm */
?>
<?php
if (!$model->isNewRecord) {

    if($model->type == 0 ) {
        $this->registerCss("
            .field-banner-code{display:none}"
        );
    }elseif ($model->type == 1){
        $this->registerCss("
            .field-banner-file{display:none}"
        );
    }
}?>

<div class="banner-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>


    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>
        </div>
    </div>

    <?= $form->field($model, 'type')->dropDownList($model->bannerType) ?>

    <?php
    if ($model->isNewRecord) {
        echo $form->field($model, 'file[]',['template' => '<label>File <span style="font-size: 12px;">(jpg,png,gif,jpeg,mp4,m4v,mov,flv,f4v,ogg,ogv,wmv,vp6,vp5,mpg,avi,mpeg,webm,swf)</label>  {input}{error}'])
            ->widget(FileInput::classname(), [
            'options' => [
                'multiple' => false,
            ],
            'pluginOptions' => [
                'allowedFileExtensions' => ["jpg", "png", "gif", "jpeg","mp4", "m4v", "mov", "flv", "f4v", "ogg", "ogv", "wmv", "vp6", "vp5", "mpg", "avi", "mpeg", "webm", "swf"],
                'showPreview' => true,
                'showCaption' => true,
                'showRemove' => true,
                'message' => "hello",
                'showUpload' => false,
                'removeLabel' => Yii::t('app', 'Удалять'),
                'browseLabel' => Yii::t('app', 'Добавить'),
                'maxFileCount' => 1,
                'initialCaption' => Yii::t('app', 'Добавить фотографии'),
                'uploadUrl' => Url::to(['#']),
                'uploadLabel' => false,
                'uploadAsync' => false,

                //previewFileType'previewFileType' => 'image'
            ]
        ]);

    }else{
           // echo  $form->field($model, 'file')->fileInput();
            echo $form->field($model, 'file[]',['template' => '<label>File <span style="font-size: 12px;">(jpg,png,gif,jpeg,mp4,m4v,mov,flv,f4v,ogg,ogv,wmv,vp6,vp5,mpg,avi,mpeg,webm,swf)</label>  {input}{error}'])
                ->widget(FileInput::classname(), [
                'options' => [
                    'multiple' => false,
                ],
                'pluginOptions' => [
                    'showPreview' => true,
                    'showRemove' => true,
                    'showUpload' => false,
                    'removeLabel' => Yii::t('app', 'Удалять'),
                    'browseLabel' => Yii::t('app', 'Добавить'),
                    'allowedFileExtensions' => ["jpg", "png", "gif", "jpeg","mp4", "m4v", "mov", "flv", "f4v", "ogg", "ogv", "wmv", "vp6", "vp5", "mpg", "avi", "mpeg", "webm", "swf"],
                    'maxFileCount' => 1,
                    'initialPreview' => $allimage,
                    'overwriteInitial' => false,
                    'initialPreviewAsData' => true,
                    'initialCaption' => Yii::t('app', 'Добавить фотографии'),
                    'initialPreviewConfig' => $allimageid,
                    "initialPreviewFileType" => $fileTypePreview,

                ]
            ]);
    }
    ?>
    <?php
    if (!$model->isNewRecord && $model->type == 1) {
        echo $form->field($model, 'code',['template' => '<label>File <span style="font-size: 12px;">(HTML,Javascript)</label>  {input}{error}'])->textarea(['rows' => 6,'value' => $model->content ]);
    }else {
        echo $form->field($model, 'code',['template' => '<label>Code <span style="font-size: 12px;">(Html,Javascript)</label>  {input}{error}'])->textarea(['rows' => 6,'value' => $model->content ]);
    }
    ?>


    <?=  $form->field($model, 'destination_url')->textInput(['maxlength' => true]);?>



    <div class="row">
        <div class="col-md-6">
            <?php // $form->field($model, 'width')->textInput() ?>
        </div>
        <div class="col-md-6">
            <?php // $form->field($model, 'height')->textInput() ?>
        </div>
    </div>


    <?php //$form->field($model, 'is_limit_ended')->dropDownList([ '1' => 'Active', '0' => 'Passive', ], ['prompt' => '']) ?>

    <div class="row">
        <div class="col-md-6">
             <?=
             $form->field($model, 'banner_page_id', ['template' => '{label}{input}{error}{hint}']
             )->widget(Select2::classname(), [
                 'data' => $model->bannerPages,
                 'language' => 'ru',
                 'options' => ['placeholder' => Yii::t('app', 'Пожалуйста, выбери Cтраница'),
                     'onchange' => '
               $.post("' . Yii::$app->request->baseUrl . '/banner/placements-age",{ id: $(this).val() },
                           function(data) {
                             var json_obj = $.parseJSON(data);
                                    $("select#banner-banner_placement_id").html(json_obj.placement); 
                           }
                                   );'],
                 'pluginOptions' => ['allowClear' => true],
             ]);
             ?>
        </div>

        <?php
        if (!$model->isNewRecord ) { ?>
            <div class="col-md-6">
                <?php  echo $form->field($model, 'banner_placement_id')->widget(Select2::classname(), [
                    'data' => $model->bannerPlacementChecked,
                    'language' => 'ru',
                    'options' => ['placeholder' => Yii::t('app', 'Пожалуйста, выбери Pазмещение'),
                    ],
                    'pluginOptions' => ['allowClear' => true],
                ]);


                ?>
            </div>
       <?php
         }else { ?>
            <div class="col-md-6">
                <?php echo $form->field($model, 'banner_placement_id')->widget(Select2::classname(), [
                    'language' => 'ru',
                    'options' => ['placeholder' => Yii::t('app', 'Пожалуйста, выбери Pазмещение'),
                    ],
                    'pluginOptions' => ['allowClear' => true],
                ]);
                ?>
            </div>
         <?php } ?>

    </div>
    <?php if($model->isNewRecord):    ?>
    <?=   $form->field($bannerCountry, 'country_include_id')->widget(Select2::classname(), [
        'data' => $model->bannerCountry,
        'options' => ['placeholder' => 'Select a Country ...', 'multiple' => true],
        'pluginOptions' => [
            'tags' => true,
            'tokenSeparators' => [',', ' '],
            'maximumInputLength' => 10
        ],
    ]);

    ?>
    <?php else: ?>
    <?=   $form->field($bannerCountry, 'country_include_id')->widget(Select2::classname(), [
        'data' => $model->bannerCountry,
        'options' => [
            'placeholder' => 'Select a Country ...',
            'multiple' => true,
            'value' => $country],
        'pluginOptions' => [
            'tags' => true,
            'tokenSeparators' => [',', ' '],
            'maximumInputLength' => 10
        ],
    ]);
    ?>
    <?php endif; ?>

    <div class="row">
        <div class="col-md-6">
            <?php $model->is_active = true;?>
            <?=   $form->field($model, "is_active")->widget(SwitchInput::classname(), [
                'type' => SwitchInput::CHECKBOX,
                'items' => [
                    ['label' => 'On', 'value' => 1],
                    ['label' => 'Off', 'value' => 0]
                ],
            ]); ?>
         </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <?= $form->field($bannerRules, 'limit_count')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($bannerRules, 'limit_days')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($bannerRules, 'limit_end_date')->widget(\yii\jui\DatePicker::classname(), [
                'language' => 'en',
                'options' => [ 'class' => 'form-control' ],
            ]) ?>
         </div>
    </div>



<?php if(!yii::$app->request->isAjax) {
    if($model->isNewRecord): ?>
    <?=  Growl::widget([
        'type' => Growl::TYPE_SUCCESS,
        'title' => 'Add Banners!',
        'icon' => 'glyphicon glyphicon-ok-sign',
        'body' => 'From here you can add your Banner',
        'showSeparator' => true,
        'delay' => 0,
        'pluginOptions' => [
            'showProgressbar' => true,
            'placement' => [
                'from' => 'top',
                'align' => 'right',
            ]
        ]
    ]);?>
<?php else: ?>
    <?=  Growl::widget([
        'type' => Growl::TYPE_SUCCESS,
        'title' => 'Update Banners!',
        'icon' => 'glyphicon glyphicon-ok-sign',
        'body' => 'From here you can update  "'.$model->name.'" Banner',
        'showSeparator' => true,
        'delay' => 0,
        'pluginOptions' => [
            'showProgressbar' => true,
            'placement' => [
                'from' => 'top',
                'align' => 'right',
            ]
        ]
    ]);?>
<?php
    endif;
} ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
<?php
 if ($model->isNewRecord) {
    $this->registerCss("
        .field-banner-code{display:none}
      
        ");
 }
?>

<?php
if (!$model->isNewRecord) {
    $this->registerJs("  
    $('#banner-type').change(function(){
        $('#banner-code').html('');
    })
    ");
}

$this->registerCss(" 
 .file-drop-zone-title{
     padding: 10px;
    }
    .file-input.file-input-ajax-new{
    padding-bottom:20px
    }
   .kv-file-upload {
    display: none !important;
    }
");
$this->registerJs("
    $('#banner-type').change(function(){
        if($(this).val() == 0){
         $('.field-banner-file').show();
         $('.field-banner-code').hide();
        } else if($(this).val() == 1){
         $('.field-banner-file').hide();
         $('.field-banner-code').show();
        }
    })
    
", \yii\web\View::POS_READY);
?>

backend/views/banner/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\BannerSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="banner-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'type') ?>

    <?= $form->field($model, 'content') ?>

    <?php // echo $form->field($model, 'destination_url') ?>

    <?php // echo $form->field($model, 'width') ?>

    <?php // echo $form->field($model, 'height') ?>

    <?php // echo $form->field($model, 'is_active') ?>

    <?php // echo $form->field($model, 'is_limit_ended') ?>

    <?php // echo $form->field($model, 'banner_placement_id') ?>

    <?php // echo $form->field($model, 'banner_page_id') ?>

    <?php // echo $form->field($model, 'banner_age_id') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/banner/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Banner */

$this->title = 'Create Banner';
$this->params['breadcrumbs'][] = ['label' => 'Banners', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="banner-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'bannerRules' => $bannerRules,
        'bannerCountry' => $bannerCountry,
    ]) ?>

</div>